<script lang="ts">
	/**
	 * AISummary - Display AI-generated natural language bark summary
	 * Fetches from /api/summary/ai endpoint powered by local Ollama
	 */

	import { marked } from 'marked';
	import type { AISummary } from '$lib/api/types';

	interface Props {
		startDate: string;
		endDate: string;
	}

	let { startDate, endDate }: Props = $props();

	let loading = $state(false);
	let error = $state<string | null>(null);
	let summary = $state<AISummary | null>(null);

	// Configure marked for safe rendering
	marked.setOptions({
		breaks: true,
		gfm: true
	});


	async function fetchSummary() {
		loading = true;
		error = null;

		try {
			// Use the new range-based AI summary endpoint
			const response = await fetch(
				`/api/summary/ai?start_date=${startDate}&end_date=${endDate}`
			);

			if (!response.ok) {
				if (response.status === 503) {
					throw new Error('Ollama service not available. Is it running?');
				}
				throw new Error(`HTTP error! status: ${response.status}`);
			}

			summary = await response.json();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to fetch AI summary';
		} finally {
			loading = false;
		}
	}
</script>

<div class="ai-summary">
	<div class="summary-header">
		<div class="header-left">
			<span class="header-icon">&#x1F916;</span>
			<span class="header-title">AI Report Summary</span>
		</div>
		<button
			class="btn btn-ghost btn-sm"
			onclick={fetchSummary}
			disabled={loading}
		>
			{loading ? 'Generating...' : summary ? 'Regenerate' : 'Generate'}
		</button>
	</div>

	{#if loading}
		<div class="summary-loading">
			<div class="loading-spinner"></div>
			<span>Analyzing bark patterns...</span>
		</div>
	{:else if error}
		<div class="summary-error">
			<span class="error-icon">&#x26A0;</span>
			<span>{error}</span>
		</div>
	{:else if summary}
		<div class="summary-content">
			<div class="summary-text markdown-content">
				{@html marked.parse(summary.summary)}
			</div>

			<div class="report-fineprint">
				<div class="fineprint-divider"></div>
				<p class="fineprint-text">
					This report was generated by <strong>Woofalytics v2.3.0</strong> automated noise monitoring system.<br>
					Detection: CLAP + YAMNet neural networks (98% confidence) •
					Dog identification: Audio fingerprint analysis<br>
					Microphone: 4-channel array with direction-of-arrival estimation •
					Summary: {summary.model} local LLM<br>
					<em>Timestamped audio evidence files available upon request.</em>
				</p>
			</div>

			<div class="summary-meta">
				<span class="meta-item">
					<span class="meta-label">Model:</span>
					<span class="meta-value">{summary.model}</span>
				</span>
				<span class="meta-item">
					<span class="meta-label">Generated in:</span>
					<span class="meta-value">{summary.generation_time_ms}ms</span>
				</span>
				<span class="meta-item">
					<span class="meta-label">Period:</span>
					<span class="meta-value">{summary.data_period}</span>
				</span>
			</div>
		</div>
	{:else}
		<div class="summary-empty">
			<p>Click "Generate" to create an AI-powered summary of bark activity for the selected period.</p>
			<p class="empty-note">Requires Ollama running locally with qwen2.5:3b model.</p>
		</div>
	{/if}
</div>

<style>
	.ai-summary {
		background: var(--bg-surface);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-md);
		padding: var(--space-lg);
	}

	.summary-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: var(--space-md);
	}

	.header-left {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
	}

	.header-icon {
		font-size: 1.25rem;
	}

	.header-title {
		font-size: 0.9rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		color: var(--text-primary);
	}

	.summary-loading {
		display: flex;
		align-items: center;
		gap: var(--space-md);
		padding: var(--space-lg);
		color: var(--text-muted);
	}

	.loading-spinner {
		width: 20px;
		height: 20px;
		border: 2px solid var(--border-muted);
		border-top-color: var(--accent-teal);
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	.summary-error {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
		padding: var(--space-md);
		background: rgba(239, 68, 68, 0.1);
		border-radius: var(--radius-sm);
		color: #f87171;
		font-size: 0.85rem;
	}

	.summary-content {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}

	.summary-text {
		font-size: 0.95rem;
		line-height: 1.7;
		color: var(--text-primary);
		margin: 0;
		padding: var(--space-lg);
		background: var(--bg-elevated);
		border-radius: var(--radius-sm);
		border-left: 3px solid var(--accent-teal);
	}

	/* Markdown content styles */
	.markdown-content :global(h1),
	.markdown-content :global(h2),
	.markdown-content :global(h3) {
		margin-top: var(--space-md);
		margin-bottom: var(--space-sm);
		font-weight: 600;
		color: var(--text-primary);
	}

	.markdown-content :global(h1) { font-size: 1.25rem; }
	.markdown-content :global(h2) { font-size: 1.1rem; }
	.markdown-content :global(h3) { font-size: 1rem; }

	.markdown-content :global(p) {
		margin: var(--space-sm) 0;
	}

	.markdown-content :global(p:first-child) {
		margin-top: 0;
	}

	.markdown-content :global(p:last-child) {
		margin-bottom: 0;
	}

	.markdown-content :global(strong) {
		color: var(--text-primary);
		font-weight: 600;
	}

	.markdown-content :global(ul),
	.markdown-content :global(ol) {
		margin: var(--space-sm) 0;
		padding-left: var(--space-lg);
	}

	.markdown-content :global(li) {
		margin: var(--space-xs) 0;
	}

	.markdown-content :global(table) {
		width: 100%;
		border-collapse: collapse;
		margin: var(--space-md) 0;
		font-size: 0.9rem;
	}

	.markdown-content :global(th),
	.markdown-content :global(td) {
		padding: var(--space-sm) var(--space-md);
		text-align: left;
		border: 1px solid var(--border-default);
	}

	.markdown-content :global(th) {
		background: var(--bg-surface);
		font-weight: 600;
		color: var(--text-primary);
	}

	.markdown-content :global(tr:nth-child(even)) {
		background: rgba(255, 255, 255, 0.02);
	}

	.markdown-content :global(hr) {
		border: none;
		border-top: 1px solid var(--border-default);
		margin: var(--space-md) 0;
	}

	.report-fineprint {
		margin-top: var(--space-md);
	}

	.fineprint-divider {
		height: 1px;
		background: linear-gradient(
			to right,
			var(--border-default),
			var(--border-muted),
			var(--border-default)
		);
		margin-bottom: var(--space-md);
	}

	.fineprint-text {
		font-size: 0.7rem;
		line-height: 1.6;
		color: var(--text-muted);
		margin: 0;
		text-align: center;
	}

	.fineprint-text strong {
		color: var(--text-secondary);
	}

	.fineprint-text em {
		display: block;
		margin-top: var(--space-xs);
		font-style: italic;
	}

	.summary-meta {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-md);
		font-size: 0.75rem;
	}

	.meta-item {
		display: flex;
		gap: var(--space-xs);
	}

	.meta-label {
		color: var(--text-muted);
	}

	.meta-value {
		color: var(--text-secondary);
		font-family: 'JetBrains Mono', monospace;
	}

	.summary-empty {
		padding: var(--space-md);
		text-align: center;
		color: var(--text-muted);
	}

	.summary-empty p {
		margin: 0;
	}

	.empty-note {
		font-size: 0.75rem;
		margin-top: var(--space-sm) !important;
		opacity: 0.7;
	}
</style>
